set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR $ENV{SYSTEM_PROCESSOR})
set(CMAKE_ANDROID_ARCH_ABI $ENV{ANDROID_ARCH_ABI})

set(CMAKE_ANDROID_STANDALONE_TOOLCHAIN $ENV{CROSS_ROOT})
set(CMAKE_ANDROID_ARM_MODE ON)
set(CMAKE_ANDROID_ARM_NEON ON)

set(CMAKE_C_COMPILER $ENV{CROSS_TRIPLE}-clang)
set(CMAKE_CXX_COMPILER $ENV{CROSS_TRIPLE}-clang++)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-llog")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-llog")

set(CMAKE_FIND_ROOT_PATH $ENV{CROSS_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_SYSROOT "$ENV{CROSS_ROOT}/sysroot")
